document.writeln(" <ul class=\'nav navbar-nav\' class=\'f_l\' id=\'menu_topleft\'>");
document.writeln("        <li><a>欢迎，<span class=\'f_red\'>客人</span></a></li>");
document.writeln("        <li><a href=\'http://39.108.163.163/gaosou/member/login.php\'>请登录</a></li>");
document.writeln("        <li><a href=\'http://39.108.163.163/gaosou/member/register.php\'>免费注册</a></li>");
document.writeln("        <li><a href=\'http://39.108.163.163/gaosou/member/send.php\'>忘记密码?</a></li>");
document.writeln("    </ul>");
document.writeln("    <ul class=\'nav navbar-nav dropdown-hover\' style=\'float: right;padding: 0;\' id=\'menu_topright\'>");
document.writeln("        <li class=\'h_mobile\' style=\'height: 32px;\'><a href=\'http://39.108.163.163/gaosou/mobile/mobile.php\'>手机版</a>&nbsp;</li>");
document.writeln("        <li class=\'dropdown nav-item has-sub\'>");
document.writeln("            <a href=\'#\' class=\'nav-item-link\'>我是雇主<span class=\'caret\'></span></a>");
document.writeln("            <ul class=\'dropdown-menu nav-item-sub nav-sub-list\'>");
document.writeln("                <li><a href=\'http://39.108.163.163/gaosou/member/login.php\'>发布任务</a></li>");
document.writeln("                <li><a href=\'http://39.108.163.163/gaosou/master/\'>找服务商</a></li>");
document.writeln("                <li><a href=\'http://39.108.163.163/gaosou/member/login.php?forward=http%3A%2F%2F39.108.163.163%2Fgaosou%2Fmember%2Fwitkey.php%3Faction%3Dwaitpay%26view%3Dtransaction%26op%3Dreleased%26intTaskStatus%3D0\'><span class=\'badge\'><?php echo $intWaitPay[\'0\'][\'count\'];?></span>待付款任务</a></li>");
document.writeln("                <li><a href=\'http://39.108.163.163/gaosou/member/login.php?forward=http%3A%2F%2F39.108.163.163%2Fgaosou%2Fmember%2Fwitkey.php%3Faction%3Dwaitselect%26view%3Dtransaction%26op%3Dreleased%26intTaskStatus%3D3\'><span class=\'badge\'><?php echo $intChoose[\'0\'][\'count\'];?></span>待选稿</a></li>");
document.writeln("                <li><a href=\'http://39.108.163.163/gaosou/member/login.php?forward=http%3A%2F%2F39.108.163.163%2Fgaosou%2Fmember%2Fwitkey.php%3Faction%3Dwaitjudge%26view%3Dgz%26op%3Dmark%26type%3D1%26nav%3D0\'><span class=\'badge\'><?php echo $intMarkG;?></span>待评价</a></li>");
document.writeln("            </ul>");
document.writeln("        </li>");
document.writeln("        <li class=\'dropdown nav-item has-sub\'>");
document.writeln("            <a href=\'#\' class=\'nav-item-link\'>我是高手<span class=\'caret\'></span></a>");
document.writeln("            <ul class=\'dropdown-menu nav-item-sub nav-sub-list\'>");
document.writeln("                <li><a href=\'http://39.108.163.163/gaosou/member/my.php\'>发布商品</a></li>");
document.writeln("                <li><a href=\'http://39.108.163.163/gaosou//com/\'>我的店铺</a></li>");
document.writeln("                <li><a href=\'http://39.108.163.163/gaosou/member/login.php?forward=http%3A%2F%2F39.108.163.163%2Fgaosou%2Fmember%2Fwitkey.php%3Faction%3Dindex'>任务订单</a></li>");
document.writeln("                <li><a href=\'http://39.108.163.163/gaosou/member/login.php?forward=http%3A%2F%2F39.108.163.163%2Fgaosou%2Fmember%2Ftrade.php\'>商城订单 </a></li>");
document.writeln("                <li><a href=\'http://39.108.163.163/gaosou/member/login.php?forward=http%3A%2F%2F39.108.163.163%2Fgaosou%2Fmember%2Fwitkey.php%3Faction%3Dwaitjudge%26view%3Dwk%26op%3Dmark%26type%3D1%26nav%3D0\'><span class=\'badge\'><?php echo $intMarkW;?></span>待评价</a></li>");
document.writeln("            </ul>");
document.writeln("        </li>");
document.writeln("        <li class=\'nav-item\'>");
document.writeln("            <a href=\'http://39.108.163.163/gaosou/index.php?do=help\' class=\'nav-item-link\'>帮助中心</a>");
document.writeln("        </li>");
document.writeln("    </ul>");